## Consider the below code to answer further questions:

In [1]:
import numpy as np
list = ['1','2','3','4','5']
array_list = np.array(object = list)

# Q 1.

## Is there any difference in the data type of variables list and array_list? If there is then write a code to print the data types of both the variables.

In [2]:
type(list)

list

In [3]:
type(array_list)

numpy.ndarray

As we can see 'list' is a List type variable where as 'array_list' is a numpy.ndarray type variable

# Q 2.

## Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [4]:
for i in list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [5]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q 3.

## Considering the following changes in the variable, array_list:

In [6]:
array_list = np.array(object = list,dtype= int )

### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [8]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


so as we can see that previously the dtype of elements present in the 'array_list' were str and now those elements types changes into int .

## Consider the below code to answer further questions:

In [9]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# Q 4.

## Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size

In [10]:
num_array.shape

(2, 3)

In [11]:
num_array.size

6

# Q 5.

## Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [15]:
zer0_mat = np.zeros((3,3))
print(zer0_mat)

print('shape',zer0_mat.shape)
print('size', zer0_mat.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
shape (3, 3)
size 9


# Q 6.

## Create an identity matrix of shape (5,5) using numpy functions?

In [17]:
identity_mat = np.eye(5,5)
identity_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])